#!/bin/bash
# Script generated by LSD
echo "Processing 43 configuration files in up to 12 parallel processes..."
if [ "$1" = "" ]; then LSD_EXEC="/home/gpetrini/LSD/Work/CodingSession/Industry_SummerSchool/lsdNW"; else LSD_EXEC="$1"; fi
if [ "$2" = "" ]; then LSD_CONFIG_PATH="/home/gpetrini/LSD/Work/CodingSession/Industry_SummerSchool/R/data"; else LSD_CONFIG_PATH="$2"; fi
echo "LSD executable: $LSD_EXEC"
echo "Configuration path: $LSD_CONFIG_PATH"
echo "Use Sim-Sobol.sh LSD_EXEC CONFIG_PATH to change default paths"
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sim-Sobol -s 1 -e 4 -p -l "$LSD_CONFIG_PATH"/Sim-Sobol_1.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sim-Sobol -s 5 -e 8 -p -l "$LSD_CONFIG_PATH"/Sim-Sobol_2.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sim-Sobol -s 9 -e 12 -p -l "$LSD_CONFIG_PATH"/Sim-Sobol_3.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sim-Sobol -s 13 -e 16 -p -l "$LSD_CONFIG_PATH"/Sim-Sobol_4.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sim-Sobol -s 17 -e 20 -p -l "$LSD_CONFIG_PATH"/Sim-Sobol_5.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sim-Sobol -s 21 -e 24 -p -l "$LSD_CONFIG_PATH"/Sim-Sobol_6.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sim-Sobol -s 25 -e 28 -p -l "$LSD_CONFIG_PATH"/Sim-Sobol_7.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sim-Sobol -s 29 -e 31 -p -l "$LSD_CONFIG_PATH"/Sim-Sobol_8.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sim-Sobol -s 32 -e 34 -p -l "$LSD_CONFIG_PATH"/Sim-Sobol_9.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sim-Sobol -s 35 -e 37 -p -l "$LSD_CONFIG_PATH"/Sim-Sobol_10.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sim-Sobol -s 38 -e 40 -p -l "$LSD_CONFIG_PATH"/Sim-Sobol_11.log &
$LSD_EXEC -c 1 -f "$LSD_CONFIG_PATH"/Sim-Sobol -s 41 -e 43 -p -l "$LSD_CONFIG_PATH"/Sim-Sobol_12.log &
echo "12 log files being generated: Sim-Sobol_1.log to Sim-Sobol_12.log ."
